import Head from "next/head"; //for meta information
import Message from "../components/message"; 
import { useEffect, useState } from "react"; // hooks for state and effects
import { db } from "../utils/firebase"; 
import { collection, onSnapshot, orderBy, query } from "firebase/firestore"; 
import Link from "next/link";

export default function Home() {
  //create a state with all posts
  const [allPosts, setAllPosts] = useState([]); //state for all posts

  const getPosts = async () => { //function to get posts
    const collectionRef = collection(db, 'posts'); //get posts collection reference
    const q = query(collectionRef, orderBy('timestamp', 'desc')); //query posts ordered by timestamp
    const unsubscribe = onSnapshot(q, (snapshot) => { 
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id }))); //set posts state
    });
    return unsubscribe;//cleanup
  };

  useEffect(() => { 
    getPosts(); //fetch posts
  }, []); //empty dependency array for one-time effect

  return (
    <div>
      <Head>
        <title>Jack's Music Notes App</title> {/* page title */}
        <meta name="description" content="Generated by create next app" /> 
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <div className="my-12 text-lg font-medium px-10"> 
        <h2>See what others are saying</h2> {/* heading for posts section */}
        {allPosts.map((post) => ( //map through all posts
          <Message key={post.id} {...post}> {/* render message component for each post */}
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}> {/* link to individual post */}
              <button className="active:text-gray-500 hover:text-gray-400"> 
                {post.comments?.length > 0 ? post.comments?.length : 0} comments {/* display number of comments (note: add comment vs comments)*/}
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </div>
  );
}
